name: Release Obsidian plugin

on:
  push:
    tags:
      - "*"   # trigger when pushing a tag

permissions:
  contents: write   # needed for gh release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Build plugin
        run: |
          npm ci
          npm run build

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          tag="${GITHUB_REF#refs/tags/}"
          echo "Creating release for tag: $tag"

          # Check the built files exist
          ls -l dist/

          gh release create "$tag" \
            --title="$tag" \
            --draft \
            dist/main.js \
            dist/manifest.json \
            dist/styles.css \
            dist/README.md
